// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PeopleFlow.Infrastructure.Persistence;

#nullable disable

namespace PeopleFlow.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PeopleFlowDbContext))]
    partial class PeopleFlowDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("PeopleFlow.Domain.Apuracao.ApuracaoDiaRegistro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("AtrasoMinutos")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<int>("AusenciaParcialMinutos")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CalculadoEm")
                        .HasColumnType("TEXT");

                    b.Property<int>("CreditoBancoMinutos")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Data")
                        .HasColumnType("TEXT");

                    b.Property<int>("DebitoBancoMinutos")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DescontoMinutos")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExtrasAPagarMinutos")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExtrasMinutos")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExtrasNoturnasMinutos")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExtrasPercentual")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FaltaMinutos")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("FuncionarioId")
                        .HasColumnType("TEXT");

                    b.Property<string>("InconsistenciasJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("IntervaloRealMinutos")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IntervaloSuprimidoMinutos")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("JornadaId")
                        .HasColumnType("TEXT");

                    b.Property<int>("NoturnoFictoMinutos")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NoturnoRealMinutos")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("PoliticaId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PrevistoJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PrevistoMinutos")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Provisorio")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RegrasJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SaidaAntecipadaMinutos")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SaldoMinutos")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SegmentosJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Situacao")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoDia")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<int>("ToleranciaDesconsideradaMinutos")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TrabalhadoMinutos")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VersaoMotor")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Data");

                    b.HasIndex("FuncionarioId", "Data")
                        .IsUnique();

                    b.ToTable("Apuracoes", (string)null);
                });

            modelBuilder.Entity("PeopleFlow.Domain.Auditoria.EventoAuditoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Acao")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("DetalhesJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("Entidade")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EntidadeId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Quando")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("TEXT");

                    b.Property<string>("UsuarioNome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Quando");

                    b.HasIndex("Entidade", "EntidadeId");

                    b.ToTable("EventosAuditoria", (string)null);
                });

            modelBuilder.Entity("PeopleFlow.Domain.BancoHoras.BancoHorasLancamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CriadoPorId")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Data")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("FechamentoId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FuncionarioId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Minutos")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("VenceEm")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FuncionarioId", "Data");

                    b.ToTable("BancoHorasLancamentos", (string)null);
                });

            modelBuilder.Entity("PeopleFlow.Domain.Empresas.Empresa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Ativa")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("TEXT");

                    b.Property<string>("Cor")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("FusoHorario")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<string>("Municipio")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeFantasia")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("Uf")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("TEXT");

                    b.Property<int>("UltimoNsr")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Cnpj")
                        .IsUnique();

                    b.ToTable("Empresas", (string)null);
                });

            modelBuilder.Entity("PeopleFlow.Domain.Empresas.PoliticaEmpresa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("AdicionalNoturnoPercentual")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CriadoPorId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DestinoHeDescansoFeriado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("DestinoHoraExtra")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly>("FimNoturno")
                        .HasColumnType("TEXT");

                    b.Property<bool>("HoraNoturnaReduzida")
                        .HasColumnType("INTEGER");

                    b.Property<TimeOnly>("InicioNoturno")
                        .HasColumnType("TEXT");

                    b.Property<int>("InterjornadaMinimaMinutos")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IntervaloMinimo4a6hMinutos")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IntervaloMinimoAcima6hMinutos")
                        .HasColumnType("INTEGER");

                    b.Property<int>("JanelaDuplicidadeMinutos")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LimiteDiarioHeMinutos")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModoTolerancia")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Observacao")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("PercentualHeDescansoFeriado")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PercentualHeDiaUtil")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ProrrogacaoNoturna")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ToleranciaDiariaMinutos")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ToleranciaPorMarcacaoMinutos")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ValidadeBancoMeses")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Versao")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("VigenteDesde")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId", "Versao")
                        .IsUnique();

                    b.ToTable("Politicas", (string)null);
                });

            modelBuilder.Entity("PeopleFlow.Domain.Feriados.Feriado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Abrangencia")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Data")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("EmpresaId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Municipio")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Uf")
                        .HasMaxLength(2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Data");

                    b.HasIndex("EmpresaId");

                    b.ToTable("Feriados", (string)null);
                });

            modelBuilder.Entity("PeopleFlow.Domain.Funcionarios.Funcionario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("CentroCusto")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("DataAdmissao")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("DataDemissao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Departamento")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("GestorId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Matricula")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Pis")
                        .HasMaxLength(11)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GestorId");

                    b.HasIndex("EmpresaId", "Matricula")
                        .IsUnique();

                    b.ToTable("Funcionarios", (string)null);
                });

            modelBuilder.Entity("PeopleFlow.Domain.Funcionarios.FuncionarioJornada", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("DataReferenciaCiclo")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FuncionarioId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("JornadaId")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("VigenteAte")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("VigenteDesde")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("JornadaId");

                    b.HasIndex("FuncionarioId", "VigenteDesde")
                        .IsUnique();

                    b.ToTable("FuncionarioJornadas", (string)null);
                });

            modelBuilder.Entity("PeopleFlow.Domain.Jornadas.Jornada", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Ativa")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("FeriadosCompensados")
                        .HasColumnType("INTEGER");

                    b.Property<TimeOnly>("HoraVirada")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.ToTable("Jornadas", (string)null);
                });

            modelBuilder.Entity("PeopleFlow.Domain.Jornadas.JornadaDia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Folga")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Indice")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("JornadaId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("JornadaId", "Indice")
                        .IsUnique();

                    b.ToTable("JornadaDias", (string)null);
                });

            modelBuilder.Entity("PeopleFlow.Domain.Jornadas.JornadaPeriodo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly>("Entrada")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("JornadaDiaId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Ordem")
                        .HasColumnType("INTEGER");

                    b.Property<TimeOnly>("Saida")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("JornadaDiaId");

                    b.ToTable("JornadaPeriodos", (string)null);
                });

            modelBuilder.Entity("PeopleFlow.Domain.Ponto.Marcacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DecididoEm")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DecididoPorId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FuncionarioId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Justificativa")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("MarcacaoAlvoId")
                        .HasColumnType("TEXT");

                    b.Property<string>("MotivoDecisao")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("Nsr")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Origem")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RegistradoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SolicitadoEm")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SolicitadoPorId")
                        .HasColumnType("TEXT");

                    b.Property<string>("StatusAjuste")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoAjuste")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DecididoPorId");

                    b.HasIndex("MarcacaoAlvoId");

                    b.HasIndex("SolicitadoPorId");

                    b.HasIndex("StatusAjuste");

                    b.HasIndex("FuncionarioId", "DataHora");

                    b.ToTable("Marcacoes", (string)null);
                });

            modelBuilder.Entity("PeopleFlow.Domain.Usuarios.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("BloqueadoAte")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CarimboSeguranca")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("FuncionarioId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Perfil")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("SenhaPadrao")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TentativasFalhas")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UltimoAcessoEm")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FuncionarioId")
                        .IsUnique();

                    b.HasIndex("Login")
                        .IsUnique();

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("PeopleFlow.Domain.Apuracao.ApuracaoDiaRegistro", b =>
                {
                    b.HasOne("PeopleFlow.Domain.Funcionarios.Funcionario", null)
                        .WithMany()
                        .HasForeignKey("FuncionarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PeopleFlow.Domain.BancoHoras.BancoHorasLancamento", b =>
                {
                    b.HasOne("PeopleFlow.Domain.Funcionarios.Funcionario", null)
                        .WithMany()
                        .HasForeignKey("FuncionarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PeopleFlow.Domain.Empresas.PoliticaEmpresa", b =>
                {
                    b.HasOne("PeopleFlow.Domain.Empresas.Empresa", null)
                        .WithMany("Politicas")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PeopleFlow.Domain.Feriados.Feriado", b =>
                {
                    b.HasOne("PeopleFlow.Domain.Empresas.Empresa", null)
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("PeopleFlow.Domain.Funcionarios.Funcionario", b =>
                {
                    b.HasOne("PeopleFlow.Domain.Empresas.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PeopleFlow.Domain.Funcionarios.Funcionario", "Gestor")
                        .WithMany()
                        .HasForeignKey("GestorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Empresa");

                    b.Navigation("Gestor");
                });

            modelBuilder.Entity("PeopleFlow.Domain.Funcionarios.FuncionarioJornada", b =>
                {
                    b.HasOne("PeopleFlow.Domain.Funcionarios.Funcionario", null)
                        .WithMany("Jornadas")
                        .HasForeignKey("FuncionarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PeopleFlow.Domain.Jornadas.Jornada", "Jornada")
                        .WithMany()
                        .HasForeignKey("JornadaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Jornada");
                });

            modelBuilder.Entity("PeopleFlow.Domain.Jornadas.Jornada", b =>
                {
                    b.HasOne("PeopleFlow.Domain.Empresas.Empresa", null)
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PeopleFlow.Domain.Jornadas.JornadaDia", b =>
                {
                    b.HasOne("PeopleFlow.Domain.Jornadas.Jornada", null)
                        .WithMany("Dias")
                        .HasForeignKey("JornadaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PeopleFlow.Domain.Jornadas.JornadaPeriodo", b =>
                {
                    b.HasOne("PeopleFlow.Domain.Jornadas.JornadaDia", null)
                        .WithMany("Periodos")
                        .HasForeignKey("JornadaDiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PeopleFlow.Domain.Ponto.Marcacao", b =>
                {
                    b.HasOne("PeopleFlow.Domain.Usuarios.Usuario", null)
                        .WithMany()
                        .HasForeignKey("DecididoPorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PeopleFlow.Domain.Funcionarios.Funcionario", "Funcionario")
                        .WithMany()
                        .HasForeignKey("FuncionarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PeopleFlow.Domain.Ponto.Marcacao", null)
                        .WithMany()
                        .HasForeignKey("MarcacaoAlvoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PeopleFlow.Domain.Usuarios.Usuario", null)
                        .WithMany()
                        .HasForeignKey("SolicitadoPorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Funcionario");
                });

            modelBuilder.Entity("PeopleFlow.Domain.Usuarios.Usuario", b =>
                {
                    b.HasOne("PeopleFlow.Domain.Funcionarios.Funcionario", "Funcionario")
                        .WithMany()
                        .HasForeignKey("FuncionarioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Funcionario");
                });

            modelBuilder.Entity("PeopleFlow.Domain.Empresas.Empresa", b =>
                {
                    b.Navigation("Politicas");
                });

            modelBuilder.Entity("PeopleFlow.Domain.Funcionarios.Funcionario", b =>
                {
                    b.Navigation("Jornadas");
                });

            modelBuilder.Entity("PeopleFlow.Domain.Jornadas.Jornada", b =>
                {
                    b.Navigation("Dias");
                });

            modelBuilder.Entity("PeopleFlow.Domain.Jornadas.JornadaDia", b =>
                {
                    b.Navigation("Periodos");
                });
#pragma warning restore 612, 618
        }
    }
}
