import { lazy } from 'react'

export const AppLayout = lazy(() => import('@/components/layout/AppLayout'))
export const LoginPage = lazy(() => import('@/features/auth/LoginPage'))
export const PainelPage = lazy(() => import('@/features/painel/PainelPage'))
export const RegistrarPontoPage = lazy(() => import('@/features/ponto/RegistrarPontoPage'))
export const EspelhoPage = lazy(() => import('@/features/ponto/EspelhoPage'))
export const AprovacoesPage = lazy(() => import('@/features/aprovacoes/AprovacoesPage'))
export const ApuracaoPage = lazy(() => import('@/features/apuracao/ApuracaoPage'))
export const BancoHorasPage = lazy(() => import('@/features/banco/BancoHorasPage'))
export const BancoFuncionarioPage = lazy(() => import('@/features/banco/BancoFuncionarioPage'))
export const EmpresasPage = lazy(() => import('@/features/empresas/EmpresasPage'))
export const EmpresaPage = lazy(() => import('@/features/empresas/EmpresaPage'))
export const JornadasPage = lazy(() => import('@/features/jornadas/JornadasPage'))
export const JornadaEditorPage = lazy(() => import('@/features/jornadas/JornadaEditorPage'))
export const FuncionariosPage = lazy(() => import('@/features/funcionarios/FuncionariosPage'))
export const FuncionarioPage = lazy(() => import('@/features/funcionarios/FuncionarioPage'))
export const UsuariosPage = lazy(() => import('@/features/usuarios/UsuariosPage'))
export const PerfilPage = lazy(() => import('@/features/perfil/PerfilPage'))
export const NotFoundPage = lazy(() => import('./NotFoundPage'))
